# Usamos la imagen oficial de Nginx basada en Alpine Linux (liviana y segura)
FROM nginx:alpine

# (Opcional) Podemos personalizar la página de bienvenida básica
RUN echo "<h1>Hola desde Nginx en GCP Class!</h1>" > /usr/share/nginx/html/index.html

# Exponer el puerto 80
EXPOSE 80
